Ajout de tests pour vérifier fonctionnement de l'app

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,10 +13,39 @@ jobs:
       # Checkout the code as the first step.
       - checkout
 
-      - run:
+      - build:
           name: Build Docker Image
           command: |
             docker build -t yannchav/node-js-sample:${CIRCLE_SHA1} .
+
+      - run:
+          name: Run Docker Image
+          command: |
+            docker run -p 8080:8080 yannchav/node-js-sample:${CIRCLE_SHA1} .
+
+      - test-home:
+          name: Verify home response
+          command: |
+            RESPONSE=$(curl -s http://localhost:8080)
+            
+            if echo "$RESPONSE" | grep -q "<h1>BackSpace Academy</h1>"; then
+              echo "Verification passed: Home contains title 'Backspace Academy'."
+            else
+              echo "Verification failed: Home does not contain 'Backspace Academy'."
+              exit 1
+            fi
+
+      - test-users:
+          name: Verify /users response
+          command: |
+            RESPONSE=$(curl -s http://localhost:8080/users)
+            
+            if echo "$RESPONSE" | grep -q "respond with a resource"; then
+              echo "Verification passed: The response contains 'respond with a resource'."
+            else
+              echo "Verification failed: The response does not contain 'respond with a resource'."
+              exit 1
+            fi
 
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
